Suppress broken semicolon_if_nothing_returned lint
Gonna assume this is due to https://github.com/rust-lang/rust-clippy/issues/7768.

    error: consider adding a `;` to the last statement for consistent formatting
       --> src/lib.rs:271:1
        |
    271 | / impl_Integer!(
    272 | |     I8_MAX_LEN => i8,
    273 | |     U8_MAX_LEN => u8,
    274 | |     I16_MAX_LEN => i16,
    ...   |
    277 | |     U32_MAX_LEN => u32
    278 | |     as u32);
        | |____________^
        |
        = note: `-D clippy::semicolon-if-nothing-returned` implied by `-D clippy::pedantic`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
    help: add a `;` here
        |
    271 + impl_Integer!(
    272 +     I8_MAX_LEN => i8,
    273 +     U8_MAX_LEN => u8,
    274 +     I16_MAX_LEN => i16,
    275 +     U16_MAX_LEN => u16,
    276 +     I32_MAX_LEN => i32,
      ...

    error: consider adding a `;` to the last statement for consistent formatting
       --> src/lib.rs:280:1
        |
    280 | impl_Integer!(I64_MAX_LEN => i64, U64_MAX_LEN => u64 as u64);
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: add a `;` here: `impl_Integer!(I64_MAX_LEN => i64, U64_MAX_LEN => u64 as u64);;`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned

    error: consider adding a `;` to the last statement for consistent formatting
       --> src/lib.rs:289:1
        |
    289 | impl_Integer!(I64_MAX_LEN => isize, U64_MAX_LEN => usize as u64);
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: add a `;` here: `impl_Integer!(I64_MAX_LEN => isize, U64_MAX_LEN => usize as u64);;`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned